[package]
name = "signal"
version = "0.1.0"
authors = ["IGI-111 <igi-111@protonmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.2"
lazy_static = "1.4.0"

[dependencies.ws]
version = "*"
features = ["ssl"]
